const ADMIN = "ADMIN";
const CUSTOMER = "CUSTOMER";
const MANAGER = "MANAGER";
const CHEF = "CHEF";
const WAITER = "WAITER";
const OWNER = "OWNER";
const ROLES = [ADMIN, CUSTOMER, MANAGER, CHEF, WAITER, OWNER];
const PENDING = "PENDING";
const PREPARING = "PREPARING";
const READY = "READY";
const SERVED = "SERVED";
const COMPLETED = "COMPLETED";
const CANCELLED = "CANCELLED";
const ORDER_STATUSES = [
  PENDING,
  PREPARING,
  READY,
  SERVED,
  COMPLETED,
  CANCELLED,
];
const TODO = "TODO";
const IN_PROGRESS = "IN_PROGRESS";
const DONE = "DONE";
const ORDER_ITEM_STATUSES = [TODO, IN_PROGRESS, DONE];

module.exports = {
  ADMIN,
  CUSTOMER,
  MANAGER,
  CHEF,
  WAITER,
  OWNER,
  ROLES,
  PENDING,
  PREPARING,
  READY,
  SERVED,
  COMPLETED,
  CANCELLED,
  ORDER_STATUSES,
  TODO,
  IN_PROGRESS,
  DONE,
  ORDER_ITEM_STATUSES,
};
